language: elixir
otp_release:
- 22.0
elixir:
- 1.9.0
env:
  global:
  - MIX_ENV=test
cache:
  directories:
  - _build
  - deps
script:
- mix test
notifications:
  email: false
  slack:
    secure: ZV+DHLuWZx3K9xxs0SJERH39Vmoa412d6FxmThd/BuwJmIX6g2i/2hV3UDZybPMTFna2NFkjsJbwzBOxXHiele1CNOkM2ofbLx1md0NdLNTNhtBHtCk5nqdOHuUUQ5VpFnpHMwAq34JVureKB2nMyHZah9ODrMci4KVmBFSZCKMhVfgSh2j66DPjDMnteRVyZxA/gwmEzXRTX+NVjmEoQAwwu5cZnTML18wissO1ps0fdhIWOODvJ6jaxCIlB9LHThFqWhYQUYtvfZl8aNbU8xcfbPSR/YmPsa1ctuUvb8qO4QOWL+9u56OH9JOkuZxvu+TYB5RqJ5usrFX5PzwfNtmcqamcw1eZ3C+Co/XVMGWgXa7PkVpEa7Sn83L8kiXurwf34BGp1OOeqQIFCJZu9S5M4HxEfkx+FFcvJmGomx3KJtVDCNZox+dOmNDiiqiOgjngkTm/94weK0m+ogfzggszxhSb7JhjNgPTx6PC9uJaIVQ1Q1ZFGcaJt1lmX6HhgY6y83b3KljD0y2NBmZoXGpEFYJ7/JKJ34pePjO14jMj3G3fqSdi5EuUxHTN6NDeGUFQTxZzaF4p2ZED3nIfDFICJ5v0fqM1Y9qs0VPXc9U1YbitDI7VVYCfrUigmGbwo5EMLAel6uI+hqmVpwkLnhavTqcy5BEhM08tkDL281I=
