language: elixir
otp_release:
  - 22
elixir:
  - 1.9.0
env:
  global:
    # Follow other language's environment
    # e.g.) `RACK_ENV=test` has been setted as Default Environment Variables
    # https://docs.travis-ci.com/user/environment-variables/#Default-Environment-Variables
    - MIX_ENV=test
cache:
  directories:
    - _build
    - deps
script:
  - mix test
notifications:
  slack:
    secure: RVFFMQofyzXUjYDgxs1nrCgM2C/sXGyN+CdoAHCItYmXp+8L6m3g9/ylhk7SJNVyuoodYBssdifS01JKnC2wB4sjSsC69JorKUuqTBcyXypQiSLA8j1cW9TwRzxVCtgoa0xfbTqTXLietaKxnkwtDzll31J5g3hQYBMcQFoTfMAzkkH/4Gn1UN1IPriO1QuySUy9hzg0W/xrIQL4PdT8unCVvUdv2wKAz0HR5YZeso1tD3L/8Ie/OmmLCTBMZBB3JPXeE4gDvotRqC+vQgaQjOxDVAtzm51wQRL//aJ/EFIgxE0b99s5y30Ne0F9zwtL8yDAotEHLKO/cNfrgVQSVNOk4J8BwfbMI4IuYjzSNpeIFpsqRiEDJ2FpxjLjO6zpAG17+wHbTm9jcUiqdOCBR6engwdTwZ1Tn75b0WOpnS/VrESmfHqeobPskA4RGTlJPebCyIkyQ5CR0jTRfBuhEJ6FlLstPWCUjaxkBkgDheY2GvwwzqWaEIune77oBzbTxrroa/K+2b4Kkw/I5/UEHzEBQYlQxDhZFaJy6PytcmRGZ3lEhflQ1ThCLcM7T4nlVJnNHdFu99vwKcAVBktYgPAZY9y1EfiNL2x9QFPkGlEbkACL6ljTCbH9L2PdWTiTVBAl8L76YQIoZbH7nXLtiHbiUERTY06DzD80NJLHA7Q=
